-- Create Users and Accounts tables
CREATE TABLE Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    ExternalId NVARCHAR(200) NOT NULL,
    FullName NVARCHAR(200) NULL,
    Email NVARCHAR(200) NULL,
    Password NVARCHAR(255) NULL,
    Phone NVARCHAR(20) NULL,
    IsActive BIT NULL DEFAULT 1,
    CardNumber NVARCHAR(16) NULL,
    PIN NVARCHAR(255) NULL,
    CardIssueDate DATETIME NULL,
    CardExpiryDate DATETIME NULL,
    CardStatus NVARCHAR(20) NULL DEFAULT 'ACTIVE',
    FailedPinAttempts INT NULL DEFAULT 0,
    CardBlocked BIT NULL DEFAULT 0,
    LastPinAttempt DATETIME NULL,
    CreatedAt DATETIME2 NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME2 NULL DEFAULT GETDATE()
);
GO


CREATE TABLE Accounts (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    UserId INT NOT NULL,
    Balance DECIMAL(18,2) NULL DEFAULT 0.00,
    Currency NVARCHAR(10) NULL DEFAULT 'SGD',
    AccountType NVARCHAR(20) NULL DEFAULT 'SAVINGS',
    Status NVARCHAR(20) NULL DEFAULT 'ACTIVE',
    AccountNumber NVARCHAR(20) NULL,
    CreatedAt DATETIME2 NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME2 NULL DEFAULT GETDATE(),
    CONSTRAINT FK_Accounts_Users FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);
