-- SQL to create UserOtps table
CREATE TABLE IF NOT EXISTS UserOtps (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Identifier NVARCHAR(200) NOT NULL,
  OtpHash NVARCHAR(255) NOT NULL,
  ExpiresAt DATETIMEOFFSET NOT NULL,
  CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
);
